import { StyleSheet } from 'react-native';
import { colors } from './home.styles';

export const chatbotStyles = StyleSheet.create({
  container: {
    position: 'absolute',
    bottom: 28,
    right: 28,
    zIndex: 999,
  },
  containerPhone: {
    bottom: 20,
    right: 20,
  },
  floatingButton: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#d0e2ef',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#17283b',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  floatingButtonPhone: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  floatingAvatar: {
    width: 38,
    height: 38,
    resizeMode: 'contain',
  },
  floatingAvatarPhone: {
    width: 34,
    height: 34,
  },
  badgeDot: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#66b28d',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  chatWindow: {
    position: 'absolute',
    bottom: 76,
    right: 0,
    width: 370,
    height: 500,
    borderRadius: 24,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dce8ef',
    shadowColor: '#17283b',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  chatWindowPhone: {
    width: 320,
    right: -4,
    bottom: 68,
    height: 440,
  },
  chatHeader: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: '#edf6fc',
    borderBottomWidth: 1,
    borderBottomColor: '#dce8ef',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerAvatar: {
    width: 36,
    height: 36,
    resizeMode: 'contain',
  },
  headerTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '800',
  },
  headerSubtitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
  headerStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.green,
  },
  headerSubtitle: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '600',
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dce8ef',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatBody: {
    flex: 1,
  },
  chatBodyContent: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  welcomeBox: {
    alignItems: 'center',
    marginBottom: 16,
    padding: 14,
    borderRadius: 18,
    backgroundColor: '#f6fafd',
    borderWidth: 1,
    borderColor: '#e4eff7',
  },
  welcomeAvatar: {
    width: 48,
    height: 48,
    resizeMode: 'contain',
    marginBottom: 8,
  },
  welcomeTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  welcomeText: {
    color: colors.muted,
    fontSize: 12,
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 18,
  },
  upcomingBadge: {
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: '#e7f3fb',
  },
  upcomingBadgeText: {
    color: colors.blueDark,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  messageGroup: {
    gap: 12,
    marginBottom: 14,
  },
  botBubble: {
    alignSelf: 'flex-start',
    maxWidth: '85%',
    padding: 12,
    borderRadius: 18,
    borderTopLeftRadius: 4,
    backgroundColor: '#edf6fc',
    borderWidth: 1,
    borderColor: '#d6e8f4',
  },
  botMessageText: {
    color: colors.ink,
    fontSize: 13,
    lineHeight: 19,
  },
  userBubble: {
    alignSelf: 'flex-end',
    maxWidth: '85%',
    padding: 12,
    borderRadius: 18,
    borderTopRightRadius: 4,
    backgroundColor: colors.blueDark,
  },
  userMessageText: {
    color: '#ffffff',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '500',
  },
  suggestionsTitle: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  suggestionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d0e2ef',
  },
  chipText: {
    color: colors.blueDark,
    fontSize: 12,
    fontWeight: '600',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#e5edf3',
    backgroundColor: '#ffffff',
  },
  textInput: {
    flex: 1,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#f2f7fa',
    borderWidth: 1,
    borderColor: '#dce8ef',
    paddingHorizontal: 14,
    fontSize: 13,
    color: colors.ink,
  },
  sendButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.blueDark,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
