import { StyleSheet } from 'react-native';

export const footerStyles = StyleSheet.create({
  footer: { position: 'relative', width: '100%', marginTop: 0, backgroundColor: '#fffdf8' },
  artworkWindow: { position: 'relative', width: '100%', height: 220, overflow: 'hidden', backgroundColor: '#fffdf8' },
  artworkWindowInternal: { height: 250 },
  artworkWindowPhone: { height: 95 },
  footerArtwork: { position: 'absolute', zIndex: 3, left: 0, right: 0, bottom: -105, width: '100%', aspectRatio: 3 },
  footerArtworkInternal: { top: -180, bottom: undefined },
  footerArtworkPhone: { top: -80, bottom: undefined, left: -70, right: undefined, width: 540, height: 180, aspectRatio: undefined },
  infoArea: { position: 'relative', minHeight: 120, paddingHorizontal: 54, paddingTop: 13, paddingBottom: 12, backgroundColor: '#fffdf8' },
  infoAreaPhone: { minHeight: 125, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 16 },
  infoRow: { width: '100%', maxWidth: 1880, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 22 },
  infoRowPhone: { gap: 12 },
  footerBrand: { paddingRight: 22, borderRightWidth: 1, borderRightColor: '#d8e2dc' },
  footerBrandPhone: { paddingRight: 0, borderRightWidth: 0 },
  footerLogo: { width: 205, height: 58 },
  footerLogoPhone: { width: 145, height: 48 },
  footerNav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 26, flex: 1 },
  footerNavItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  footerNavText: { color: '#587083', fontSize: 14, fontWeight: '600' },
  footerEnd: { flexDirection: 'row', alignItems: 'center', gap: 18 },
  footerEndPhone: { gap: 8 },
  socials: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingRight: 22, borderRightWidth: 1, borderRightColor: '#d8e2dc' },
  legalLinks: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  legalLinkText: { color: '#587083', fontSize: 12, fontWeight: '600' },
  legalSeparator: { color: '#91a29b', fontSize: 12 },
  copyright: { color: '#71877e', fontSize: 11, textAlign: 'center', marginTop: 8 },
});
