import { StyleSheet } from "react-native";

export const colors = {
  ink: "#17283b",
  muted: "#728092",
  blue: "#3f719b",
  blueDark: "#2b5479",
  sky: "#e7f3fb",
  border: "#e5edf3",
  white: "#ffffff",
  green: "#66b28d",
  coral: "#d8957d",
};

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: "#f2f7fa" },
  header: {
    backgroundColor: "transparent",
  },
  headerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  headerScrolled: {
    backgroundColor: "rgba(251, 253, 255, 0.97)",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerInner: {
    width: "100%",
    maxWidth: 1920,
    minHeight: 86,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 54,
    gap: 72,
    position: "relative",
  },
  headerInnerCompact: { minHeight: 72, paddingHorizontal: 20, gap: 12 },
  brand: { flexDirection: "row", alignItems: "center", gap: 14 },
  brandMark: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: "#f0f6fb",
    borderWidth: 1,
    borderColor: "#dfebf4",
    alignItems: "center",
    justifyContent: "center",
  },
  brandMarkText: {
    color: colors.blueDark,
    fontSize: 34,
    fontWeight: "800",
    lineHeight: 36,
  },
  brandLogo: { width: 43, height: 43 },
  brandLogoFull: { width: 158, height: 54 },
  brandName: {
    color: colors.ink,
    fontSize: 21,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  brandAccent: { color: colors.blue },
  brandTagline: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 1.2,
    marginTop: 1,
  },
  nav: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
    gap: 20,
  },
  navItem: { height: 46, justifyContent: "center", alignItems: "center", flexDirection: "row", gap: 8, position: "relative", paddingHorizontal: 17, borderRadius: 24 },
  navItemActive: { backgroundColor: "#fff4d5" },
  navText: { color: "#5d7180", fontSize: 14, fontWeight: "600" },
  navTextActive: { color: colors.blueDark, fontSize: 14, fontWeight: "800" },
  headerActions: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 12,
  },
  weatherPill: { flexDirection: "row", alignItems: "center", gap: 8, marginRight: 8 },
  weatherIcon: { color: "#efb92f", fontSize: 27 },
  weatherCity: { color: colors.blueDark, fontSize: 11, fontWeight: "700" },
  weatherTemp: { color: colors.blueDark, fontSize: 11, fontWeight: "800" },
  serviceStatus: {
    height: 48,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 17,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    backgroundColor: colors.white,
  },
  serviceText: { color: "#667384", fontSize: 15 },
  iconButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  notificationAnchor: { position: "relative", zIndex: 120 },
  notificationPopover: {
    position: "absolute",
    top: 62,
    right: 0,
    width: 288,
    padding: 18,
    borderRadius: 18,
    backgroundColor: "#fbfdff",
    borderWidth: 1,
    borderColor: "#dce8ef",
    shadowColor: "#17283b",
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 30,
    zIndex: 130,
  },
  notificationPopoverCompact: { right: -8, width: 270 },
  notificationPopoverPhone: {
    position: "absolute",
    top: 70,
    left: 12,
    right: 12,
    padding: 18,
    borderRadius: 18,
    backgroundColor: "#fbfdff",
    borderWidth: 1,
    borderColor: "#dce8ef",
    shadowColor: "#17283b",
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  notificationPopoverHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  notificationPopoverTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "800",
  },
  notificationClose: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationEmptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#eaf4fa",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 18,
  },
  notificationEmptyTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 12,
  },
  notificationEmptyText: {
    color: colors.muted,
    fontSize: 13,
    textAlign: "center",
    marginTop: 5,
  },
  loginButton: {
    height: 46,
    paddingHorizontal: 25,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#5a87aa",
  },
  loginText: { color: colors.white, fontWeight: "700", fontSize: 14 },
  scrollContent: { flexGrow: 1 },
  hero: {
    backgroundColor: "#fbf8eb",
    minHeight: 430,
    paddingHorizontal: 54,
    overflow: "hidden",
  },
  heroImage: {
    position: "absolute",
    left: "38%",
    width: "62%",
    height: "100%",
  },
  heroOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(255, 248, 226, 0.04)",
  },
  heroCreamPanel: {
    position: "absolute",
    top: -165,
    bottom: -145,
    left: -80,
    width: "49%",
    minWidth: 610,
    borderTopRightRadius: 360,
    borderBottomRightRadius: 360,
    backgroundColor: "rgba(255, 252, 241, 0.94)",
  },
  heroCreamBubble: {
    position: "absolute",
    top: -210,
    left: "18%",
    width: 560,
    height: 360,
    borderRadius: 280,
    backgroundColor: "rgba(255, 252, 241, 0.72)",
  },
  heroSkyBubble: {
    position: "absolute",
    top: -190,
    left: "27%",
    width: 620,
    height: 280,
    borderRadius: 310,
    backgroundColor: "rgba(236, 247, 250, 0.54)",
  },
  heroInner: {
    width: "100%",
    maxWidth: 1920,
    alignSelf: "center",
    paddingTop: 92,
    paddingBottom: 24,
    position: "relative",
  },
  heroInnerCompact: { paddingTop: 98, paddingBottom: 48 },
  locationPill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: colors.white,
    borderRadius: 22,
    paddingHorizontal: 17,
    height: 42,
  },
  locationText: {
    color: "#717b87",
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 1.1,
  },
  heroTitle: {
    color: colors.ink,
    fontSize: 40,
    lineHeight: 44,
    fontWeight: "800",
    letterSpacing: -1.2,
    marginTop: 0,
    maxWidth: 470,
  },
  heroTitleCompact: {
    fontSize: 41,
    lineHeight: 47,
    letterSpacing: -1,
    marginTop: 26,
  },
  heroTitleBlue: { color: colors.blueDark },
  heroTunjaRow: { flexDirection: "row", alignItems: "center", alignSelf: "flex-start", marginTop: -2 },
  heroTitleGreen: { color: "#5aaa6d", fontSize: 52, lineHeight: 57, fontFamily: "Segoe Print", fontStyle: "italic", fontWeight: "700" },
  heroAccentMarks: { width: 34, height: 44, marginLeft: 4, position: "relative" },
  heroAccentMark: { position: "absolute", width: 18, height: 5, borderRadius: 4, backgroundColor: "#f5c537" },
  heroAccentMarkTop: { top: 4, left: 3, transform: [{ rotate: "-58deg" }] },
  heroAccentMarkMiddle: { top: 20, left: 10, transform: [{ rotate: "-5deg" }] },
  heroAccentMarkBottom: { top: 34, left: 3, transform: [{ rotate: "48deg" }] },
  heroDescription: {
    color: colors.blueDark,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 12,
    maxWidth: 470,
  },
  heroLeaf: { position: "absolute", left: "34%", top: 168, width: 96, height: 96, opacity: 0.78, transform: [{ rotate: "-20deg" }] },
  heroSloganWrap: { position: "absolute", left: "49%", top: 126, flexDirection: "row", alignItems: "flex-end", transform: [{ rotate: "-4deg" }] },
  heroSlogan: { color: colors.blueDark, fontSize: 28, lineHeight: 31, fontFamily: "Segoe Print", fontStyle: "italic", fontWeight: "700" },
  heroSloganAccent: { width: 30, height: 42, marginLeft: 1, marginBottom: 2, position: "relative" },
  homeQuickActions: {
    flexDirection: "row",
    gap: 11,
    marginTop: 22,
    flexWrap: "wrap",
  },
  searchRow: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 14,
    marginTop: 0,
  },
  searchRowCompact: { marginTop: 0, gap: 12 },
  searchBox: {
    flex: 1,
    maxWidth: 1245,
    minHeight: 98,
    borderRadius: 31,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#7d9bb0",
    shadowOpacity: 0.1,
    shadowRadius: 13,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
    paddingLeft: 34,
    paddingRight: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
  },
  searchBoxCompact: {
    minHeight: 78,
    borderRadius: 24,
    paddingLeft: 20,
    gap: 10,
  },
  searchFields: { width: "100%", gap: 10 },
  searchFieldsInline: { flexDirection: "row", flexWrap: "wrap" },
  searchFieldRow: { flexDirection: "row", alignItems: "center", width: "100%", gap: 8 },
  searchFieldRowInline: { flex: 1, minWidth: 0 },
  searchLocationAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 5,
    paddingHorizontal: 4,
  },
  searchLocationActionText: { color: colors.blue, fontSize: 13, fontWeight: "600" },
  searchInput: { flex: 1, minWidth: 0, color: colors.ink, fontSize: 21 },
  searchDivider: { height: 49, width: 1, backgroundColor: colors.border },
  locationAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 20,
  },
  locationActionText: { color: "#718092", fontSize: 16 },
  searchButton: {
    minWidth: 158,
    height: 61,
    borderRadius: 22,
    backgroundColor: "#5786aa",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  searchButtonText: { color: colors.white, fontSize: 17, fontWeight: "700" },
  quickActions: {
    position: "absolute",
    top: 0,
    left: 0,
    flexDirection: "row",
    gap: 12,
    alignSelf: "flex-start",
  },
  quickPill: {
    height: 46,
    paddingHorizontal: 15,
    borderRadius: 24,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  quickPillActive: { backgroundColor: "#edf6fc", borderColor: "#cfe2ef" },
  quickPillBlue: { backgroundColor: "#eef9fe", borderColor: "#b8dce9" },
  quickPillGreen: { backgroundColor: "#eff9ee", borderColor: "#c7e4c9" },
  quickPillGold: { backgroundColor: "#fff8df", borderColor: "#f2dda2" },
  quickPillPurple: { backgroundColor: "#f7edfb", borderColor: "#e1c8ef" },
  quickText: { color: "#526978", fontSize: 12, fontWeight: "600" },
  quickTextActive: { color: colors.blueDark, fontSize: 12, fontWeight: "800" },
  belowFold: {
    paddingHorizontal: 44,
    paddingVertical: 54,
    maxWidth: 1820,
    width: "100%",
    alignSelf: "center",
  },
  exploreSection: {
    paddingHorizontal: 54,
    paddingTop: 34,
    paddingBottom: 12,
    maxWidth: 1820,
    width: "100%",
    alignSelf: "center",
    backgroundColor: "#fffdf8",
  },
  exploreHeadingRow: { flexDirection: "row", alignItems: "center", gap: 14, paddingLeft: 8 },
  exploreHeadingIcon: { width: 48, height: 48, alignItems: "center", justifyContent: "center" },
  exploreTitle: { color: colors.ink, fontSize: 28, lineHeight: 32, fontWeight: "800" },
  exploreDescription: { color: "#667b89", fontSize: 14, lineHeight: 20, fontWeight: "500", marginTop: 2 },
  exploreLeafLeft: { position: "absolute", left: -105, top: -8, width: 130, height: 130, opacity: 0.78, transform: [{ rotate: "18deg" }] },
  exploreLeafRight: { position: "absolute", right: -108, top: -15, width: 142, height: 142, opacity: 0.82, transform: [{ rotate: "-24deg" }] },
  mapSearchBarWrap: {
    position: "absolute",
    top: 96,
    left: 24,
    right: 440,
    zIndex: 4,
  },
  mapDescriptionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
    marginTop: 8,
  },
  mapLocationAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  mapLocationActionText: { color: colors.blue, fontSize: 13, fontWeight: "600" },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    gap: 24,
    marginTop: 64,
  },
  sectionEyebrow: {
    color: colors.coral,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 30,
    fontWeight: "800",
    marginTop: 10,
  },
  sectionDescription: {
    color: "#1d405d",
    fontSize: 16,
    fontWeight: "500",
    marginTop: 8,
  },
  sectionLink: {
    color: colors.blueDark,
    fontSize: 15,
    fontWeight: "700",
    paddingBottom: 5,
  },
  routeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 18,
    marginTop: 20,
  },
  routeCard: {
    flexGrow: 1,
    flexBasis: 250,
    minHeight: 132,
    padding: 18,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e3eae8",
    boxShadow: "0 8px 20px rgba(78, 102, 108, 0.10)",
    position: "relative",
  },
  routeCardHovered: {
    backgroundColor: "#fff8df",
    borderColor: "#edcf83",
    shadowColor: "#d6ad55",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    transform: [{ translateY: -3 }],
  },
  routeCardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  routeCode: {
    borderRadius: 18,
    paddingHorizontal: 13,
    paddingVertical: 6,
    fontSize: 12,
    fontWeight: "800",
  },
  routeCodeBlue: { backgroundColor: "#1686bd", color: colors.white },
  routeCodeGreen: { backgroundColor: "#55aa60", color: colors.white },
  routeCodeGold: { backgroundColor: "#f1b51b", color: colors.white },
  routeCodeCoral: { backgroundColor: "#b84bd7", color: colors.white },
  routeCardTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "800",
    marginTop: 11,
  },
  routeCardDescription: { color: colors.muted, fontSize: 13, marginTop: 9 },
  routeCardDivider: { height: 1, backgroundColor: "#e5edf2", marginTop: 20 },
  routeCardMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
    marginTop: 10,
  },
  routeMetaItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  routeMetaText: { color: "#405a6b", fontSize: 12, fontWeight: "600" },
  routeBusIcon: { position: "absolute", right: 18, bottom: 14 },
  routesHeadingRow: { flexDirection: "row", alignItems: "center", gap: 13 },
  routesHeadingIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: "#dff2ee", alignItems: "center", justifyContent: "center" },
  routesSectionTitle: { color: colors.ink, fontSize: 24, lineHeight: 28, fontWeight: "800" },
  routesSectionDescription: { color: "#667b89", fontSize: 13, lineHeight: 18, marginTop: 2 },
  metaSeparator: { width: 1, height: 14, backgroundColor: "#dce5eb" },
  mapSection: { marginTop: 0, position: "relative" },
  mapRouteLayout: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 26,
    marginTop: 20,
  },
  mapRouteLayoutCompact: { flexDirection: "column", marginTop: 24 },
  mapContainer: {
    flex: 1,
    minWidth: 0,
    minHeight: 600,
    marginTop: 0,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  selectedRouteCard: {
    width: 390,
    minHeight: 600,
    padding: 25,
    borderRadius: 28,
    backgroundColor: "rgba(255,255,255,0.97)",
    borderWidth: 1,
    borderColor: "#dce8ef",
    boxShadow: "0 12px 32px rgba(71, 101, 116, 0.12)",
    elevation: 2,
  },
  selectedRouteCardCompact: { width: "100%" },
  routeRecommendationRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  routeRecommendationBadge: { color: "#459b68", backgroundColor: "#e8f6e9", borderRadius: 14, paddingHorizontal: 11, paddingVertical: 6, fontSize: 11, fontWeight: "800" },
  routeFastBadge: { color: colors.blueDark, backgroundColor: "#eef6fa", borderRadius: 14, paddingHorizontal: 11, paddingVertical: 6, fontSize: 11, fontWeight: "800" },
  selectedRouteHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  selectedRouteEyebrow: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  selectedRouteTitle: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: "800",
    marginTop: 3,
  },
  selectedRouteCode: {
    color: colors.blueDark,
    backgroundColor: "#edf4f8",
    borderRadius: 18,
    paddingHorizontal: 13,
    paddingVertical: 8,
    fontSize: 13,
    fontWeight: "800",
  },
  selectedRouteHeaderActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  saveRouteHeaderButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.white, borderWidth: 1, borderColor: "#dce8ef", alignItems: "center", justifyContent: "center" },
  routeStats: { flexDirection: "row", gap: 8, marginTop: 18, paddingBottom: 17, borderBottomWidth: 1, borderBottomColor: "#edf1f3" },
  routeStat: {
    flex: 1,
    minHeight: 32,
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  routeStatValue: { color: colors.ink, fontSize: 12, fontWeight: "800" },
  routeStatLabel: { color: colors.muted, fontSize: 11, marginTop: 6 },
  selectedBusOption: { minHeight: 66, marginTop: 16, padding: 10, borderRadius: 16, borderWidth: 1, borderColor: "#e2e9e5", backgroundColor: colors.white, flexDirection: "row", alignItems: "center", gap: 12 },
  selectedBusCode: { color: colors.white, backgroundColor: "#55ae68", borderRadius: 12, paddingHorizontal: 14, paddingVertical: 11, fontSize: 13, fontWeight: "900" },
  selectedBusCopy: { flex: 1, minWidth: 0 },
  selectedBusName: { color: colors.ink, fontSize: 13, fontWeight: "800" },
  selectedBusFare: { color: colors.muted, fontSize: 11, marginTop: 4 },
  itineraryTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "700",
    marginTop: 29,
  },
  itineraryList: { marginTop: 13, flex: 1 },
  itineraryRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  itineraryRail: {
    width: 20,
    alignItems: "center",
    position: "relative",
    minHeight: 64,
  },
  itineraryDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.blue,
    backgroundColor: colors.white,
    zIndex: 1,
  },
  itineraryDotFinal: { borderColor: colors.coral },
  itineraryLine: {
    position: "absolute",
    top: 12,
    bottom: 0,
    width: 1,
    backgroundColor: "#d7e2e9",
  },
  itineraryCopy: { flex: 1, paddingLeft: 10 },
  itineraryName: { color: colors.ink, fontSize: 14, fontWeight: "700" },
  itineraryDetail: { color: colors.muted, fontSize: 12, marginTop: 5 },
  itineraryTime: { color: colors.muted, fontSize: 12, paddingTop: 1 },
  startTripButton: {
    height: 56,
    borderRadius: 28,
    backgroundColor: "#2f9d73",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
  },
  startTripButtonActive: {
    backgroundColor: "#4e9b78",
  },
  startTripButtonText: { color: colors.white, fontSize: 16, fontWeight: "700" },
  routeDetailsButton: { height: 42, borderRadius: 21, borderWidth: 1, borderColor: "#cfe2ef", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5, marginTop: 10 },
  routeDetailsButtonText: { color: colors.blueDark, fontSize: 13, fontWeight: "700" },
  routeModalBackdrop: { flex: 1, backgroundColor: "rgba(23, 40, 59, 0.48)", justifyContent: "center", alignItems: "center", padding: 20 },
  routeModalCard: { width: "100%", maxWidth: 500, backgroundColor: colors.white, borderRadius: 24, padding: 22, overflow: "hidden" },
  routeModalContent: { width: "100%" },
  routeModalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 16 },
  routeModalTitleWrap: { flex: 1, minWidth: 0 },
  routeModalTitle: { color: colors.ink, fontSize: 22, lineHeight: 28, fontWeight: "800", marginTop: 6, flexShrink: 1 },
  routeModalClose: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: "#f1f5f8" },
  routeModalCategory: { color: colors.muted, fontSize: 12, fontWeight: "700", letterSpacing: 0.7, marginTop: 8 },
  routeModalColumns: { flexDirection: "row", gap: 16, marginTop: 14 },
  routeModalColumnsPhone: { flexDirection: "column" },
  routeModalInfoColumn: { flex: 1, minWidth: 0 },
  routeModalSignColumn: { flex: 1.22, minWidth: 0, alignItems: "center" },
  busSign: { width: "78%", minHeight: 250, marginTop: 0, borderRadius: 16, overflow: "hidden", borderWidth: 3, borderColor: "#17283b", backgroundColor: "#eff8df", alignItems: "center" },
  busSignCode: { alignSelf: "center", backgroundColor: "#d92828", paddingHorizontal: 16, paddingVertical: 6, borderBottomLeftRadius: 10, borderBottomRightRadius: 10 },
  busSignCodeText: { color: colors.white, fontSize: 20, fontWeight: "900" },
  busSignLabel: { color: "#495967", fontSize: 9, fontWeight: "800", letterSpacing: 1, paddingHorizontal: 12, paddingTop: 16, textAlign: "center" },
  busSignDestinations: { width: "100%", justifyContent: "center", paddingHorizontal: 12, paddingBottom: 14, paddingTop: 8 },
  busSignDestination: { color: "#d92828", fontSize: 16, lineHeight: 21, fontWeight: "900", fontStyle: "italic", textAlign: "center", flexShrink: 1 },
  busSignDestinationAccent: { color: "#2f9a44" },
  routeModalHint: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 10 },
  routeModalSchedule: { padding: 13, borderRadius: 14, backgroundColor: "#eef9f2" },
  routeModalScheduleTitle: { color: "#166534", fontSize: 14, fontWeight: "800", marginBottom: 6 },
  routeModalText: { color: "#25613f", fontSize: 12, lineHeight: 18 },
  farePanel: { marginTop: 12, padding: 13, borderRadius: 14, backgroundColor: "#f4f7fa", borderWidth: 1, borderColor: "#e0e9ef" },
  farePanelTitle: { color: colors.ink, fontSize: 14, fontWeight: "800", marginBottom: 6 },
  farePanelText: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  routeModalMapNote: { color: colors.blueDark, fontSize: 12, fontWeight: "600", marginTop: 12 },
  saveRouteButton: {
    position: "absolute",
    right: 28,
    bottom: 28,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#dce8ef",
    alignItems: "center",
    justifyContent: "center",
  },
  saveRouteButtonActive: {
    backgroundColor: "#fcf8ee",
    borderColor: "#e8c97e",
  },
  insightsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 22,
    marginTop: 36,
  },
  insightPanel: {
    flexGrow: 1,
    flexBasis: 420,
    minHeight: 232,
    padding: 20,
    borderRadius: 22,
    backgroundColor: "#fbfdff",
    borderWidth: 1,
    borderColor: "#dce8ef",
    boxShadow: "0 7px 18px rgba(88, 111, 116, 0.07)",
  },
  insightPanelBlue: { flexGrow: 1.6, flexBasis: 650, backgroundColor: "#f3fbff", borderColor: "#cfe3ef" },
  insightPanelGreen: { flexGrow: 1, flexBasis: 400, backgroundColor: "#f1fbf2", borderColor: "#cbe7d1" },
  insightPanelHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 15 },
  insightTitleRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  insightTitle: { color: colors.ink, fontSize: 16, fontWeight: "800" },
  insightDescription: { color: colors.muted, fontSize: 12, marginTop: 4, marginLeft: 30 },
  insightLink: { color: colors.blueDark, fontSize: 12, fontWeight: "700", paddingTop: 2 },
  popularPlacesGrid: { flexDirection: "row", gap: 12, marginTop: 14 },
  popularPlaceCard: { flex: 1, minWidth: 0, height: 142, borderRadius: 14, overflow: "hidden", backgroundColor: colors.white, borderWidth: 1, borderColor: "#dce7e8" },
  popularPlaceImage: { width: "100%", height: 94 },
  popularPlaceFooter: { flex: 1, flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 9 },
  popularPlaceTitle: { flex: 1, minWidth: 0, color: colors.ink, fontSize: 11, fontWeight: "800" },
  popularPlaceArrow: { width: 23, height: 23, borderRadius: 12, backgroundColor: "#f2f6f7", alignItems: "center", justifyContent: "center" },
  recommendationList: { marginTop: 18 },
  recommendationRow: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    borderBottomWidth: 1,
    borderBottomColor: "#d9e8ef",
  },
  recommendationIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f0f6fa",
    borderWidth: 1,
    borderColor: "#d4e5ed",
    alignItems: "center",
    justifyContent: "center",
  },
  recommendationCopy: { flex: 1, minWidth: 0 },
  recommendationTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  recommendationTitle: { color: colors.ink, fontSize: 14, fontWeight: "700" },
  recommendationTag: {
    color: "#5f9b7f",
    backgroundColor: "#e4f3eb",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: "700",
  },
  recommendationDescription: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 5,
  },
  recommendationDuration: { color: colors.muted, fontSize: 12 },
  recentList: { gap: 1, marginTop: 13, marginLeft: 6, borderLeftWidth: 1, borderLeftColor: "#9bd2aa" },
  recentRow: {
    minHeight: 50,
    paddingVertical: 5,
    paddingLeft: 18,
  },
  recentRoute: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    position: "relative",
  },
  recentDot: {
    position: "absolute",
    left: -22,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: "#57b66c",
  },
  recentText: { flex: 1, color: "#46606d", fontSize: 12, fontWeight: "600" },
  recentDate: {
    color: colors.muted,
    fontSize: 11,
    marginTop: 3,
  },
  historyButton: {
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: "#cfe3dc",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
  },
  historyButtonText: {
    color: colors.blueDark,
    fontSize: 13,
    fontWeight: "600",
  },
  saveRouteButtonPhone: { right: 20, bottom: 20 },
  headerInnerPhone: { minHeight: 60, paddingHorizontal: 10, gap: 4, position: "relative" },
  brandPhone: { gap: 6, flexShrink: 1 },
  brandMarkPhone: { width: 40, height: 40, borderRadius: 13 },
  brandLogoPhone: { width: 31, height: 31 },
  brandLogoFullPhone: { width: 120, height: 42 },
  brandNamePhone: { fontSize: 16, letterSpacing: -0.3 },
  brandTaglinePhone: { fontSize: 8, letterSpacing: 0.7 },
  iconButtonPhone: { width: 38, height: 38, borderRadius: 19 },
  mobileNavMenu: {
    position: "absolute",
    top: 66,
    right: 10,
    width: 172,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 6,
    shadowColor: "#17283b",
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 12,
  },
  mobileNavBackdrop: { flex: 1, backgroundColor: "transparent" },
  mobileNavItem: { paddingHorizontal: 14, paddingVertical: 11, borderRadius: 9 },
  mobileNavItemActive: { backgroundColor: "#edf6fc" },
  mobileNavText: { color: colors.muted, fontSize: 14, fontWeight: "600" },
  mobileNavTextActive: { color: colors.blueDark, fontSize: 14, fontWeight: "800" },
  loginButtonPhone: {
    height: 38,
    minWidth: 66,
    paddingHorizontal: 11,
    borderRadius: 19,
  },
  loginTextPhone: { fontSize: 13 },
  // En web móvil la búsqueda tiene dos campos, acciones y accesos rápidos.
  // Esta altura evita que los accesos se superpongan sobre “Calcular ruta”.
  heroPhone: { minHeight: 680, paddingHorizontal: 20 },
  heroImagePhone: {
    left: 0,
    width: "100%",
    height: "100%",
    transform: [{ scale: 1.02 }],
  },
  heroFadePhone: { display: "none" },
  heroInnerPhone: { paddingTop: 104, paddingBottom: 40 },
  locationPillPhone: {
    height: 36,
    borderRadius: 18,
    paddingHorizontal: 13,
    gap: 7,
  },
  locationTextPhone: { fontSize: 12, letterSpacing: 0.8 },
  heroTitlePhone: {
    color: "#142b40",
    fontSize: 31,
    lineHeight: 37,
    letterSpacing: -0.7,
    marginTop: 20,
  },
  heroDescriptionPhone: {
    color: colors.blueDark,
    fontSize: 15,
    lineHeight: 23,
    marginTop: 16,
    maxWidth: 340,
  },
  searchBoxPhone: {
    minHeight: 178,
    borderRadius: 20,
    paddingLeft: 14,
    paddingRight: 14,
    gap: 8,
  },
  searchInputPhone: { fontSize: 16 },
  searchButtonPhone: { minWidth: 102, height: 50, borderRadius: 17, gap: 6 },
  searchButtonTextPhone: { fontSize: 15 },
  exploreSectionPhone: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 48,
  },
  mapSearchBarWrapPhone: {
    position: "relative",
    top: 0,
    right: 0,
    width: "100%",
    minWidth: 0,
    marginTop: 14,
    marginBottom: 8,
  },
  mapDescriptionRowPhone: { flexWrap: "wrap", gap: 4 },
  sectionHeaderRowPhone: { alignItems: "flex-end", marginTop: 42, gap: 8 },
  sectionHeaderCopy: { flex: 1, minWidth: 0 },
  sectionLinkPhone: { fontSize: 14, paddingBottom: 2, flexShrink: 0 },
  sectionLinkBelowPhone: {
    alignSelf: "center",
    marginTop: 20,
    paddingVertical: 10,
    paddingHorizontal: 18,
  },
  sectionTitlePhone: { fontSize: 26, marginTop: 8 },
  sectionDescriptionPhone: {
    color: "#1d405d",
    fontSize: 15,
    fontWeight: "500",
    lineHeight: 21,
    marginTop: 7,
  },
  routeGridPhone: { gap: 12, marginTop: 20 },
  routeCardPhone: {
    flexBasis: "100%",
    minHeight: 156,
    padding: 18,
    borderRadius: 20,
  },
  routeCardTitlePhone: { fontSize: 16, marginTop: 15 },
  routeCardDescriptionPhone: { fontSize: 12, marginTop: 7 },
  routeCardDividerPhone: { marginTop: 16 },
  routeCardMetaPhone: { marginTop: 11 },
  mapContainerPhone: { minHeight: 360, borderRadius: 20 },
  selectedRouteCardPhone: { minHeight: 0, padding: 20, borderRadius: 20 },
  insightsGridPhone: { gap: 16, marginTop: 34 },
  insightPanelPhone: { flexBasis: "100%", padding: 20, borderRadius: 20 },
  insightTitlePhone: { fontSize: 18 },
  recommendationListPhone: { marginTop: 14 },
  recommendationRowPhone: { minHeight: 64, gap: 10 },
  recommendationIconPhone: { width: 36, height: 36, borderRadius: 18 },
  recommendationTitlePhone: { fontSize: 13 },
  recommendationDescriptionPhone: { fontSize: 11, marginTop: 3 },
  recommendationDurationPhone: { fontSize: 11 },
  recentListPhone: { marginTop: 16 },
  recentRowPhone: { padding: 13, borderRadius: 16 },
  searchRowPhone: { flexDirection: "column", alignItems: "stretch", gap: 16 },
  quickActionsPhone: { gap: 8, paddingBottom: 2 },
  homeQuickActionsPhone: { flexWrap: "wrap", gap: 8, marginTop: 24 },
  quickPillPhone: {
    height: 40,
    paddingHorizontal: 10,
    borderRadius: 20,
    gap: 8,
  },
  quickTextPhone: { fontSize: 14 },
});
