import { StyleSheet } from "react-native";

export const colors = {
  ink: "#17283b",
  muted: "#728092",
  blue: "#3f719b",
  blueDark: "#2b5479",
  sky: "#e7f3fb",
  border: "#e5edf3",
  white: "#ffffff",
  green: "#66b28d",
  coral: "#d8957d",
};

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.white },
  header: {
    backgroundColor: "#fbfdff",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerInner: {
    width: "100%",
    maxWidth: 1820,
    minHeight: 88,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 44,
    gap: 68,
  },
  headerInnerCompact: { minHeight: 72, paddingHorizontal: 20, gap: 12 },
  brand: { flexDirection: "row", alignItems: "center", gap: 14 },
  brandMark: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: "#f0f6fb",
    borderWidth: 1,
    borderColor: "#dfebf4",
    alignItems: "center",
    justifyContent: "center",
  },
  brandMarkText: {
    color: colors.blueDark,
    fontSize: 34,
    fontWeight: "800",
    lineHeight: 36,
  },
  brandName: {
    color: colors.ink,
    fontSize: 21,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  brandAccent: { color: colors.blue },
  brandTagline: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 1.2,
    marginTop: 1,
  },
  nav: {
    flexDirection: "row",
    alignItems: "stretch",
    alignSelf: "stretch",
    gap: 38,
  },
  navItem: { justifyContent: "center", position: "relative" },
  navItemActive: { borderBottomWidth: 2, borderBottomColor: "#e7c59b" },
  navText: { color: "#586576", fontSize: 17 },
  navTextActive: { color: colors.ink, fontSize: 17, fontWeight: "700" },
  headerActions: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 12,
  },
  serviceStatus: {
    height: 48,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 17,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    backgroundColor: colors.white,
  },
  serviceText: { color: "#667384", fontSize: 15 },
  iconButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  loginButton: {
    height: 52,
    paddingHorizontal: 29,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#5a87aa",
  },
  loginText: { color: colors.white, fontWeight: "700", fontSize: 16 },
  scrollContent: { flexGrow: 1 },
  hero: { backgroundColor: colors.sky, minHeight: 620, paddingHorizontal: 44 },
  heroInner: {
    width: "100%",
    maxWidth: 1820,
    alignSelf: "center",
    paddingTop: 86,
    paddingBottom: 64,
  },
  locationPill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: colors.white,
    borderRadius: 22,
    paddingHorizontal: 17,
    height: 42,
  },
  locationText: {
    color: "#717b87",
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 1.1,
  },
  heroTitle: {
    color: colors.ink,
    fontSize: 58,
    lineHeight: 67,
    fontWeight: "800",
    letterSpacing: -1.8,
    marginTop: 32,
    maxWidth: 690,
  },
  heroTitleCompact: {
    fontSize: 41,
    lineHeight: 47,
    letterSpacing: -1,
    marginTop: 26,
  },
  heroTitleBlue: { color: colors.blueDark },
  heroDescription: {
    color: "#7a8794",
    fontSize: 19,
    lineHeight: 30,
    marginTop: 23,
    maxWidth: 780,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 22,
    marginTop: 52,
  },
  searchRowCompact: { marginTop: 34 },
  searchBox: {
    flex: 1,
    maxWidth: 1245,
    minHeight: 98,
    borderRadius: 31,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#7d9bb0",
    shadowOpacity: 0.1,
    shadowRadius: 13,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
    paddingLeft: 34,
    paddingRight: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
  },
  searchBoxCompact: {
    minHeight: 78,
    borderRadius: 24,
    paddingLeft: 20,
    gap: 10,
  },
  searchInput: { flex: 1, minWidth: 0, color: colors.ink, fontSize: 21 },
  searchDivider: { height: 49, width: 1, backgroundColor: colors.border },
  locationAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 20,
  },
  locationActionText: { color: "#718092", fontSize: 16 },
  searchButton: {
    minWidth: 158,
    height: 61,
    borderRadius: 22,
    backgroundColor: "#5786aa",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  searchButtonText: { color: colors.white, fontSize: 17, fontWeight: "700" },
  quickActions: { flexDirection: "row", gap: 12 },
  quickPill: {
    height: 52,
    paddingHorizontal: 19,
    borderRadius: 27,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  quickPillActive: { backgroundColor: "#edf6fc", borderColor: "#cfe2ef" },
  quickText: { color: "#788492", fontSize: 16 },
  quickTextActive: { color: colors.blueDark, fontSize: 16, fontWeight: "600" },
  belowFold: {
    paddingHorizontal: 44,
    paddingVertical: 54,
    maxWidth: 1820,
    width: "100%",
    alignSelf: "center",
  },
  sectionEyebrow: {
    color: colors.coral,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 30,
    fontWeight: "800",
    marginTop: 10,
  },
});
