import { StyleSheet } from "react-native";

export const colors = {
  ink: "#17283b",
  muted: "#728092",
  blue: "#3f719b",
  blueDark: "#2b5479",
  sky: "#e7f3fb",
  border: "#e5edf3",
  white: "#ffffff",
  green: "#66b28d",
  coral: "#d8957d",
};

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: "#f2f7fa" },
  header: {
    backgroundColor: "transparent",
  },
  headerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  headerScrolled: {
    backgroundColor: "rgba(251, 253, 255, 0.97)",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerInner: {
    width: "100%",
    maxWidth: 1820,
    minHeight: 88,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 44,
    gap: 68,
    position: "relative",
  },
  headerInnerCompact: { minHeight: 72, paddingHorizontal: 20, gap: 12 },
  brand: { flexDirection: "row", alignItems: "center", gap: 14 },
  brandMark: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: "#f0f6fb",
    borderWidth: 1,
    borderColor: "#dfebf4",
    alignItems: "center",
    justifyContent: "center",
  },
  brandMarkText: {
    color: colors.blueDark,
    fontSize: 34,
    fontWeight: "800",
    lineHeight: 36,
  },
  brandLogo: { width: 43, height: 43 },
  brandName: {
    color: colors.ink,
    fontSize: 21,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  brandAccent: { color: colors.blue },
  brandTagline: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 1.2,
    marginTop: 1,
  },
  nav: {
    flexDirection: "row",
    alignItems: "stretch",
    alignSelf: "stretch",
    gap: 38,
  },
  navItem: { justifyContent: "center", position: "relative" },
  navItemActive: { borderBottomWidth: 2, borderBottomColor: "#e7c59b" },
  navText: { color: "#586576", fontSize: 17 },
  navTextActive: { color: colors.ink, fontSize: 17, fontWeight: "700" },
  headerActions: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 12,
  },
  serviceStatus: {
    height: 48,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 17,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    backgroundColor: colors.white,
  },
  serviceText: { color: "#667384", fontSize: 15 },
  iconButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  notificationAnchor: { position: "relative", zIndex: 20 },
  notificationPopover: {
    position: "absolute",
    top: 62,
    right: 0,
    width: 288,
    padding: 18,
    borderRadius: 18,
    backgroundColor: "#fbfdff",
    borderWidth: 1,
    borderColor: "#dce8ef",
    shadowColor: "#17283b",
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  notificationPopoverCompact: { right: -8, width: 270 },
  notificationPopoverHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  notificationPopoverTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "800",
  },
  notificationClose: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationEmptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#eaf4fa",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 18,
  },
  notificationEmptyTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 12,
  },
  notificationEmptyText: {
    color: colors.muted,
    fontSize: 13,
    textAlign: "center",
    marginTop: 5,
  },
  loginButton: {
    height: 52,
    paddingHorizontal: 29,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#5a87aa",
  },
  loginText: { color: colors.white, fontWeight: "700", fontSize: 16 },
  scrollContent: { flexGrow: 1 },
  hero: {
    backgroundColor: colors.white,
    minHeight: 700,
    paddingHorizontal: 44,
    overflow: "hidden",
  },
  heroImage: {
    resizeMode: "cover",
    transform: [{ scale: 1.08 }, { translateX: 72 }],
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(43, 84, 121, 0.10)",
  },
  heroFadeLayerOne: {
    ...StyleSheet.absoluteFillObject,
    width: 72,
    backgroundColor: "rgba(255, 255, 255, 0.30)",
  },
  heroFadeLayerTwo: {
    ...StyleSheet.absoluteFillObject,
    width: 124,
    backgroundColor: "rgba(255, 255, 255, 0.20)",
  },
  heroFadeLayerThree: {
    ...StyleSheet.absoluteFillObject,
    width: 176,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
  },
  heroFadeLayerFour: {
    ...StyleSheet.absoluteFillObject,
    width: 232,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
  },
  heroInner: {
    width: "100%",
    maxWidth: 1820,
    alignSelf: "center",
    paddingTop: 132,
    paddingBottom: 64,
  },
  heroInnerCompact: { paddingTop: 98, paddingBottom: 48 },
  locationPill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: colors.white,
    borderRadius: 22,
    paddingHorizontal: 17,
    height: 42,
  },
  locationText: {
    color: "#717b87",
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 1.1,
  },
  heroTitle: {
    color: colors.ink,
    fontSize: 58,
    lineHeight: 67,
    fontWeight: "800",
    letterSpacing: -1.8,
    marginTop: 32,
    maxWidth: 690,
  },
  heroTitleCompact: {
    fontSize: 41,
    lineHeight: 47,
    letterSpacing: -1,
    marginTop: 26,
  },
  heroTitleBlue: { color: colors.blueDark },
  heroDescription: {
    color: colors.blueDark,
    fontSize: 19,
    lineHeight: 30,
    marginTop: 23,
    maxWidth: 780,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 22,
    marginTop: 52,
  },
  searchRowCompact: { marginTop: 34 },
  searchBox: {
    flex: 1,
    maxWidth: 1245,
    minHeight: 98,
    borderRadius: 31,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#7d9bb0",
    shadowOpacity: 0.1,
    shadowRadius: 13,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
    paddingLeft: 34,
    paddingRight: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
  },
  searchBoxCompact: {
    minHeight: 78,
    borderRadius: 24,
    paddingLeft: 20,
    gap: 10,
  },
  searchInput: { flex: 1, minWidth: 0, color: colors.ink, fontSize: 21 },
  searchDivider: { height: 49, width: 1, backgroundColor: colors.border },
  locationAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 20,
  },
  locationActionText: { color: "#718092", fontSize: 16 },
  searchButton: {
    minWidth: 158,
    height: 61,
    borderRadius: 22,
    backgroundColor: "#5786aa",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  searchButtonText: { color: colors.white, fontSize: 17, fontWeight: "700" },
  quickActions: { flexDirection: "row", gap: 12 },
  quickPill: {
    height: 52,
    paddingHorizontal: 19,
    borderRadius: 27,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  quickPillActive: { backgroundColor: "#edf6fc", borderColor: "#cfe2ef" },
  quickText: { color: "#788492", fontSize: 16 },
  quickTextActive: { color: colors.blueDark, fontSize: 16, fontWeight: "600" },
  belowFold: {
    paddingHorizontal: 44,
    paddingVertical: 54,
    maxWidth: 1820,
    width: "100%",
    alignSelf: "center",
  },
  exploreSection: {
    paddingHorizontal: 44,
    paddingTop: 58,
    paddingBottom: 76,
    maxWidth: 1820,
    width: "100%",
    alignSelf: "center",
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    gap: 24,
    marginTop: 64,
  },
  sectionEyebrow: {
    color: colors.coral,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 30,
    fontWeight: "800",
    marginTop: 10,
  },
  sectionDescription: { color: "#1d405d", fontSize: 16, fontWeight: "500", marginTop: 8 },
  sectionLink: {
    color: colors.blueDark,
    fontSize: 15,
    fontWeight: "700",
    paddingBottom: 5,
  },
  routeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginTop: 26,
  },
  routeCard: {
    flexGrow: 1,
    flexBasis: 250,
    minHeight: 184,
    padding: 20,
    borderRadius: 22,
    backgroundColor: "#fbfdff",
    borderWidth: 1,
    borderColor: "#dce8ef",
    shadowColor: "#7a9aac",
    shadowOpacity: 0.09,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  routeCardHovered: {
    backgroundColor: "#fff8df",
    borderColor: "#edcf83",
    shadowColor: "#d6ad55",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    transform: [{ translateY: -3 }],
  },
  routeCardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  routeCode: {
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 7,
    fontSize: 12,
    fontWeight: "800",
  },
  routeCodeBlue: { backgroundColor: "#e2f0fa", color: colors.blueDark },
  routeCodeGreen: { backgroundColor: "#e4f3eb", color: "#5f9b7f" },
  routeCodeGold: { backgroundColor: "#f4efe4", color: "#9b835d" },
  routeCodeCoral: { backgroundColor: "#f5e9e4", color: "#a16b57" },
  routeCardTitle: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: "800",
    marginTop: 18,
  },
  routeCardDescription: { color: colors.muted, fontSize: 13, marginTop: 9 },
  routeCardDivider: { height: 1, backgroundColor: "#e5edf2", marginTop: 20 },
  routeCardMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    marginTop: 13,
  },
  routeMetaItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  routeMetaText: { color: "#718092", fontSize: 12 },
  metaSeparator: { width: 1, height: 14, backgroundColor: "#dce5eb" },
  mapSection: { marginTop: 0 },
  mapRouteLayout: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 24,
    marginTop: 24,
  },
  mapRouteLayoutCompact: { flexDirection: "column" },
  mapContainer: {
    flex: 1,
    minWidth: 0,
    minHeight: 620,
    marginTop: 0,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  selectedRouteCard: {
    width: 390,
    minHeight: 620,
    padding: 28,
    borderRadius: 24,
    backgroundColor: "#fbfdff",
    borderWidth: 1,
    borderColor: "#dce8ef",
    shadowColor: "#7a9aac",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  selectedRouteCardCompact: { width: "100%" },
  selectedRouteHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  selectedRouteEyebrow: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  selectedRouteTitle: {
    color: colors.ink,
    fontSize: 25,
    fontWeight: "800",
    marginTop: 14,
  },
  selectedRouteCode: {
    color: colors.blueDark,
    backgroundColor: "#edf4f8",
    borderRadius: 18,
    paddingHorizontal: 13,
    paddingVertical: 8,
    fontSize: 13,
    fontWeight: "800",
  },
  routeStats: { flexDirection: "row", gap: 10, marginTop: 28 },
  routeStat: {
    flex: 1,
    minHeight: 76,
    borderRadius: 20,
    backgroundColor: "#f2f6f9",
    alignItems: "center",
    justifyContent: "center",
  },
  routeStatValue: { color: colors.ink, fontSize: 17, fontWeight: "800" },
  routeStatLabel: { color: colors.muted, fontSize: 11, marginTop: 6 },
  itineraryTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "700",
    marginTop: 29,
  },
  itineraryList: { marginTop: 13, flex: 1 },
  itineraryRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  itineraryRail: {
    width: 20,
    alignItems: "center",
    position: "relative",
    minHeight: 64,
  },
  itineraryDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.blue,
    backgroundColor: colors.white,
    zIndex: 1,
  },
  itineraryDotFinal: { borderColor: colors.coral },
  itineraryLine: {
    position: "absolute",
    top: 12,
    bottom: 0,
    width: 1,
    backgroundColor: "#d7e2e9",
  },
  itineraryCopy: { flex: 1, paddingLeft: 10 },
  itineraryName: { color: colors.ink, fontSize: 14, fontWeight: "700" },
  itineraryDetail: { color: colors.muted, fontSize: 12, marginTop: 5 },
  itineraryTime: { color: colors.muted, fontSize: 12, paddingTop: 1 },
  startTripButton: {
    height: 56,
    borderRadius: 28,
    backgroundColor: "#5786aa",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
  },
  startTripButtonActive: {
    backgroundColor: "#4e9b78",
  },
  startTripButtonText: { color: colors.white, fontSize: 16, fontWeight: "700" },
  saveRouteButton: {
    position: "absolute",
    right: 28,
    bottom: 28,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#dce8ef",
    alignItems: "center",
    justifyContent: "center",
  },
  saveRouteButtonActive: {
    backgroundColor: "#fcf8ee",
    borderColor: "#e8c97e",
  },
  insightsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 20,
    marginTop: 54,
  },
  insightPanel: {
    flexGrow: 1,
    flexBasis: 420,
    padding: 26,
    borderRadius: 24,
    backgroundColor: "#fbfdff",
    borderWidth: 1,
    borderColor: "#dce8ef",
    shadowColor: "#7a9aac",
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  insightPanelBlue: { backgroundColor: "#edf7fc", borderColor: "#cfe3ef" },
  insightPanelGreen: { backgroundColor: "#eef8f4", borderColor: "#d2e8dd" },
  insightTitleRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  insightTitle: { color: colors.ink, fontSize: 19, fontWeight: "800" },
  insightDescription: { color: colors.muted, fontSize: 13, marginTop: 8 },
  recommendationList: { marginTop: 18 },
  recommendationRow: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    borderBottomWidth: 1,
    borderBottomColor: "#d9e8ef",
  },
  recommendationIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f0f6fa",
    borderWidth: 1,
    borderColor: "#d4e5ed",
    alignItems: "center",
    justifyContent: "center",
  },
  recommendationCopy: { flex: 1, minWidth: 0 },
  recommendationTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  recommendationTitle: { color: colors.ink, fontSize: 14, fontWeight: "700" },
  recommendationTag: {
    color: "#5f9b7f",
    backgroundColor: "#e4f3eb",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: "700",
  },
  recommendationDescription: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 5,
  },
  recommendationDuration: { color: colors.muted, fontSize: 12 },
  recentList: { gap: 10, marginTop: 20 },
  recentRow: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#f3f7fa",
    borderWidth: 1,
    borderColor: "#d6e8df",
  },
  recentRoute: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  recentDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.blue,
  },
  recentText: { color: colors.ink, fontSize: 13, fontWeight: "600" },
  recentDate: {
    color: colors.muted,
    fontSize: 11,
    marginTop: 6,
    marginLeft: 15,
  },
  historyButton: {
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: "#cfe3dc",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
  },
  historyButtonText: {
    color: colors.blueDark,
    fontSize: 13,
    fontWeight: "600",
  },
  saveRouteButtonPhone: { right: 20, bottom: 20 },
  headerInnerPhone: { minHeight: 64, paddingHorizontal: 16, gap: 8 },
  brandPhone: { gap: 9 },
  brandMarkPhone: { width: 48, height: 48, borderRadius: 15 },
  brandLogoPhone: { width: 37, height: 37 },
  brandNamePhone: { fontSize: 18, letterSpacing: -0.3 },
  brandTaglinePhone: { fontSize: 9, letterSpacing: 0.9 },
  iconButtonPhone: { width: 44, height: 44, borderRadius: 22 },
  loginButtonPhone: { height: 44, minWidth: 82, paddingHorizontal: 16, borderRadius: 22 },
  loginTextPhone: { fontSize: 15 },
  heroPhone: { minHeight: 530, paddingHorizontal: 20 },
  heroImagePhone: { transform: [{ scale: 1 }] },
  heroFadePhone: { display: "none" },
  heroInnerPhone: { paddingTop: 104, paddingBottom: 40 },
  locationPillPhone: { height: 36, borderRadius: 18, paddingHorizontal: 13, gap: 7 },
  locationTextPhone: { fontSize: 12, letterSpacing: 0.8 },
  heroTitlePhone: { color: "#142b40", fontSize: 31, lineHeight: 37, letterSpacing: -0.7, marginTop: 20 },
  heroDescriptionPhone: { color: colors.blueDark, fontSize: 15, lineHeight: 23, marginTop: 16, maxWidth: 340 },
  searchBoxPhone: { minHeight: 66, borderRadius: 20, paddingLeft: 16, paddingRight: 8, gap: 8 },
  searchInputPhone: { fontSize: 16 },
  searchButtonPhone: { minWidth: 102, height: 50, borderRadius: 17, gap: 6 },
  searchButtonTextPhone: { fontSize: 15 },
  exploreSectionPhone: { paddingHorizontal: 20, paddingTop: 38, paddingBottom: 48 },
  sectionHeaderRowPhone: { alignItems: "flex-end", marginTop: 42, gap: 8 },
  sectionHeaderCopy: { flex: 1, minWidth: 0 },
  sectionLinkPhone: { fontSize: 14, paddingBottom: 2, flexShrink: 0 },
  sectionLinkBelowPhone: { alignSelf: "center", marginTop: 20, paddingVertical: 10, paddingHorizontal: 18 },
  sectionTitlePhone: { fontSize: 26, marginTop: 8 },
  sectionDescriptionPhone: { color: "#1d405d", fontSize: 15, fontWeight: "500", lineHeight: 21, marginTop: 7 },
  routeGridPhone: { gap: 12, marginTop: 20 },
  routeCardPhone: { flexBasis: "100%", minHeight: 156, padding: 18, borderRadius: 20 },
  routeCardTitlePhone: { fontSize: 16, marginTop: 15 },
  routeCardDescriptionPhone: { fontSize: 12, marginTop: 7 },
  routeCardDividerPhone: { marginTop: 16 },
  routeCardMetaPhone: { marginTop: 11 },
  mapContainerPhone: { minHeight: 360, borderRadius: 20 },
  selectedRouteCardPhone: { minHeight: 0, padding: 20, borderRadius: 20 },
  insightsGridPhone: { gap: 16, marginTop: 34 },
  insightPanelPhone: { flexBasis: "100%", padding: 20, borderRadius: 20 },
  insightTitlePhone: { fontSize: 18 },
  recommendationListPhone: { marginTop: 14 },
  recommendationRowPhone: { minHeight: 64, gap: 10 },
  recommendationIconPhone: { width: 36, height: 36, borderRadius: 18 },
  recommendationTitlePhone: { fontSize: 13 },
  recommendationDescriptionPhone: { fontSize: 11, marginTop: 3 },
  recommendationDurationPhone: { fontSize: 11 },
  recentListPhone: { marginTop: 16 },
  recentRowPhone: { padding: 13, borderRadius: 16 },
  searchRowPhone: { flexDirection: "column", alignItems: "stretch", gap: 12 },
  quickActionsPhone: { gap: 8 },
  quickPillPhone: { height: 40, paddingHorizontal: 10, borderRadius: 20, gap: 8 },
  quickTextPhone: { fontSize: 14 },
});
